mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  host: db
  username: root
  password: 123456
  pool: 5
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *mysql
  database: photo_gallery_development
test:
  <<: *mysql
  database: photo_gallery_test
production:
  <<: *postgres
  database: photo_gallery_production
  username: photo_gallery
  password: <%= ENV['PHOTO_GALLERY_PASSWORD'] %>
